### ISSUE TITLE
Toggle Sort

### ISSUE THREAD

**Issue by JUG1T3R** [NonlinearFruit/Retrospector-Android#5]
Sort data in descending order by date added so you can see the most recent entries at the top.

**Comment by JUG1T3R** [comment]
^Sort by descending order by default but also have an option for the user to change the sort into alphabetical order. 

Or just have a toggle sort option where it switches between descending, alphabetical, categorical, and rating.

**Comment by NonlinearFruit** [comment]
Descending sort is would be awesome! It would give you an idea of how old your data is and allow you to easily find recent reviews.

**Comment by NonlinearFruit** [comment]
Sadly, do to my lack of android knowledge/the way it is setup. I don't think I can dynamically change the ordering (via user input) :frowning_face:
